apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "todo"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: todo-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP